import { type SearchUser } from "./types";
import {
    CS2_LOGO as cs2Logo,
    RDR2_LOGO as rdr2Logo,
    RAFT_LOGO as raftLogo,
    DEFAULT_AVATAR as defaultAvatar,
} from "@/shared/constants/images";

export const MOCK_USERS: SearchUser[] = [
    {
        id: "ghostrider",
        name: "GhostRider",
        username: "@ghostrider",
        avatar: rdr2Logo,
        bio: "Red Dead Redemption 2 enthusiast. Outlaw by day, sheriff by night.",
        status: "online",
        game: "Red Dead Redemption 2",
        isFriend: true,
    },
    {
        id: "tactical_xeno",
        name: "TacticalXeno",
        username: "@tactical_xeno",
        avatar: cs2Logo,
        bio: "Pro CS2 competitive player & tactical leader. Always online for rank pushes!",
        status: "in-game",
        game: "Counter-Strike 2",
        isFriend: true,
    },
    {
        id: "nightowl",
        name: "NightOwl",
        username: "@nightowl",
        avatar: raftLogo,
        bio: "Late night gaming (1 AM - 5 AM). Raft Hardcore survivor & fortress architect.",
        status: "online",
        game: "Raft Hardcore",
        isFriend: true,
    },
    {
        id: "maplestrike",
        name: "Maplestrike",
        username: "@maplestrike",
        avatar: defaultAvatar,
        bio: "Casual gamer exploring indie titles and RPGs. Weekend warrior.",
        status: "offline",
        game: null,
        isFriend: true,
    },
    {
        id: "user123",
        name: "User123",
        username: "@user123",
        avatar: raftLogo,
        bio: "Survival game builder, streamer and content creator. Check out my Raft ocean base!",
        status: "online",
        game: "Raft",
        isFriend: false,
    },
    {
        id: "s1mple_olex",
        name: "S1mple_Olex",
        username: "@s1mple_olex",
        avatar: cs2Logo,
        bio: "CS2 Premier 20k+ Elo AWP main. Looking for disciplined teammates.",
        status: "in-game",
        game: "Counter-Strike 2",
        isFriend: false,
    },
    {
        id: "arthur_morgan_99",
        name: "Arthur_Morgan_99",
        username: "@arthur_morgan_99",
        avatar: rdr2Logo,
        bio: "Van der Linde gang veteran. Outlaw for life, hunting legendaries in RDR2.",
        status: "online",
        game: "Red Dead Redemption 2",
        isFriend: false,
    },
    {
        id: "tacticalgamer",
        name: "TacticalGamer",
        username: "@tacticalgamer",
        avatar: cs2Logo,
        bio: "FPS aim trainer & tactical lineup guide author. Premier CS2 grinder.",
        status: "online",
        game: "Counter-Strike 2",
        isFriend: false,
    },
];
