import { type NotificationItem } from "./types";

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
    {
        id: "notif-1",
        userId: "user-current",
        type: "like",
        referenceId: "post-1",
        title: "GamerX99 đã thích bài viết của bạn",
        message: "Chê Counter-Strike 2 hack nhiều quá, Valve tính làm gì đây? 😂",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=GamerX99",
        createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
        isRead: false,
        link: "/post/1",
    },
    {
        id: "notif-2",
        userId: "user-current",
        type: "comment",
        referenceId: "post-2",
        title: "NeoCyber đã bình luận bài viết của bạn",
        message: "\"Cảm ơn bạn đã chia sẻ tips build thuyền trong Raft, cực kỳ hữu ích luôn!\"",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=NeoCyber",
        createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        isRead: false,
        link: "/post/2",
    },
    {
        id: "notif-3",
        userId: "user-current",
        type: "system",
        referenceId: "game-cs2",
        title: "Thông báo hệ thống từ Valve",
        message: "Counter-Strike 2 vừa phát hành bản cập nhật mới (Armory Patch). Vào xem ngay các thay đổi vũ khí và skin!",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Valve",
        createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        isRead: false,
        link: "/game/counter-strike-2",
    },
    {
        id: "notif-4",
        userId: "user-current",
        type: "community",
        referenceId: "comm-cs2-vn",
        title: "Sự kiện Cộng đồng",
        message: "Chào mừng những đồng đội mới tham gia cùng bạn trên cộng đồng CS2 Vietnam Competitive!",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Shouko",
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        isRead: true,
        link: "/community",
    },
    {
        id: "notif-5",
        userId: "user-current",
        type: "system",
        referenceId: "game-rdr2",
        title: "Sự kiện cuối tuần: Red Dead Redemption 2",
        message: "Giảm giá đặc biệt và nhân đôi XP trong chế độ Red Dead Online tuần này.",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Rockstar",
        createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        isRead: true,
        link: "/game/red-dead-redemption-2",
    },
];
