import {
    CS2_LOGO as cs2Logo,
    RAFT_LOGO as raftLogo,
    RDR2_LOGO as rdr2Logo,
    DEFAULT_AVATAR as avatarDefault
} from "@/shared/constants/images";
import { getCurrentAuthor } from "@/features/post/helpers/getCurrentAuthor";
import { type Squad, type SquadVoiceType } from "./types";

export const GAME_OPTIONS = [
    "Counter Strike 2",
    "Valorant",
    "League of Legends",
    "Dota 2",
    "Apex Legends",
    "PUBG",
    "Genshin Impact",
    "Minecraft",
    "Grand Theft Auto V",
    "Elden Ring",
    "Raft",
    "Red Dead Redemption 2",
    "Cyberpunk 2077",
    "Khác...",
];

export const GAME_FILTERS = [
    "all",
    ...GAME_OPTIONS.filter((g) => g !== "Khác..."),
];

export const QUICK_TAGS = [
    "🤝 Tìm Đồng Đội",
    "No Toxic",
    "Try Hard",
    "Chill",
    "Coop",
    "Ranked",
    "Hardcore",
    "Equal Pay",
    "Newbie Friendly",
    "Voice Required",
];

export const VOICE_OPTIONS: { value: SquadVoiceType; label: string }[] = [
    { value: "Discord Required", label: "🎧 Bắt buộc có Mic Discord" },
    { value: "In-game Voice", label: "🎙️ Voice chat trong game" },
    { value: "Optional", label: "👌 Có mic hay không đều được" },
    { value: "No Mic", label: "🔇 Chỉ chat text / No Mic" },
];

export const INITIAL_SQUADS: Squad[] = [
    {
        id: "squad-0",
        name: "CS2 Premier Tryhard — Đội của bạn (Chủ phòng)",
        game: "Counter Strike 2",
        gameLogo: cs2Logo,
        description: "Tổ đội do bạn làm Trưởng phòng (Leader). Bạn có toàn quyền quản lý: Kick thành viên, Khóa/Mở tuyển, Giải tán đội. Mã phòng & link Discord hiển thị đầy đủ cho thành viên.",
        tags: ["👑 Chủ Phòng", "🏆 Competitive", "Premier", "No Toxic"],
        currentMembers: 4,
        maxMembers: 5,
        voice: "Discord Required",
        isMySquad: true,
        roomCode: "#CS2-MYROOM-999",
        discordUrl: "https://discord.gg/my-cs2-squad",
        createdAt: "10 phút trước",
        status: "recruiting",
        members: [
            { id: "m-my-1", username: getCurrentAuthor(), avatar: cs2Logo, role: "Leader", status: "in-game", playtime: "2h 15m" },
            { id: "m-my-2", username: "ToxicPlayer99", avatar: rdr2Logo, role: "Member", status: "online", playtime: "1h 10m" },
            { id: "m-my-3", username: "ProCarry2k", avatar: avatarDefault, role: "Member", status: "in-game", playtime: "3h 40m" },
            { id: "m-my-4", username: "ChillGuy88", avatar: raftLogo, role: "Member", status: "online", playtime: "45m" },
        ],
    },
    {
        id: "squad-1",
        name: "Raft Hardcore Survival Veterans",
        game: "Raft",
        gameLogo: raftLogo,
        description: "Cần tìm thêm 2 anh em có mic discord chinh phục chế độ Hardcore coop từ con số 0. Không toxic, chia sẻ tài nguyên và cùng xây dựng hạm đội nổi trên biển!",
        tags: ["🤝 Tìm Đồng Đội", "Hardcore", "Coop", "No Toxic"],
        currentMembers: 3,
        maxMembers: 5,
        voice: "Discord Required",
        isMySquad: true,
        roomCode: "#RAFT-8841",
        discordUrl: "https://discord.gg/raft-vets",
        createdAt: "30 phút trước",
        status: "recruiting",
        members: [
            { id: "m-1", username: "NightOwl", avatar: raftLogo, role: "Leader", status: "in-game", playtime: "1h 03m" },
            { id: "m-2", username: "GhostRider", avatar: rdr2Logo, role: "Member", status: "online", playtime: "2h 14m" },
            { id: "m-3", username: getCurrentAuthor(), avatar: avatarDefault, role: "Member", status: "online", playtime: "45m" },
        ],
    },
    {
        id: "squad-2",
        name: "CS2 Rank S — Premier Rush B Squad",
        game: "Counter Strike 2",
        gameLogo: cs2Logo,
        description: "Tuyển 2 tay súng Entry Fragger & Support có rank Premier 15k+ hoặc Faceit level 7+. Call info net, không blame đồng đội, chiến tối nay từ 20h30.",
        tags: ["🏆 Competitive", "Premier", "Rush B", "Try Hard"],
        currentMembers: 3,
        maxMembers: 5,
        voice: "Discord Required",
        isMySquad: true,
        roomCode: "#CS2-PREM-99",
        discordUrl: "https://discord.gg/cs2-rushb",
        createdAt: "2 giờ trước",
        status: "recruiting",
        members: [
            { id: "m-4", username: "TacticalXeno", avatar: cs2Logo, role: "Leader", status: "in-game", playtime: "45m" },
            { id: "m-5", username: "ProSniper", avatar: avatarDefault, role: "Member", status: "online", playtime: "3h" },
            { id: "m-6", username: "ViperKing", avatar: cs2Logo, role: "Member", status: "online", playtime: "1h 12m" },
        ],
    },
    {
        id: "squad-3",
        name: "Valorant Ascendant Grinders — Try Hard",
        game: "Valorant",
        gameLogo: cs2Logo, // fallback logo
        description: "Tìm 2 bạn chơi vị trí Controller (Omen/Viper) và Initiator (Sova/Fade) để leo rank Ascendant tối nay. Đã có Duelist cứng và Sentinel.",
        tags: ["🤝 Tìm Đồng Đội", "Ranked", "Ascendant", "Tactical"],
        currentMembers: 3,
        maxMembers: 5,
        voice: "In-game Voice",
        isMySquad: false,
        roomCode: "#VAL-ASC-772",
        createdAt: "4 giờ trước",
        status: "recruiting",
        members: [
            { id: "m-7", username: "CyberSamurai", avatar: avatarDefault, role: "Leader", status: "in-game", playtime: "2h 30m" },
            { id: "m-8", username: "ChillVibes", avatar: rdr2Logo, role: "Member", status: "online", playtime: "1h" },
            { id: "m-9", username: "Elena_V", avatar: cs2Logo, role: "Member", status: "online", playtime: "15m" },
        ],
    },
    {
        id: "squad-4",
        name: "Red Dead Online — Posse Heist & Bounty",
        game: "Red Dead Redemption 2",
        gameLogo: rdr2Logo,
        description: "Tuyển anh em nhập hội Posse đi săn tiền thưởng Huyền thoại (Legendary Bounty) và áp tải hàng hoá đường dài. Vui vẻ nhí nhố là chính!",
        tags: ["🤠 Western", "Bounty Hunting", "Coop", "Chill"],
        currentMembers: 4,
        maxMembers: 7,
        voice: "Optional",
        isMySquad: true,
        roomCode: "#RDR-POSSE-01",
        createdAt: "5 giờ trước",
        status: "recruiting",
        members: [
            { id: "m-10", username: "LosSantosBro", avatar: rdr2Logo, role: "Leader", status: "online", playtime: "3h" },
            { id: "m-11", username: "TarnishedOne", avatar: avatarDefault, role: "Member", status: "in-game", playtime: "1h" },
            { id: "m-12", username: "MapMaker", avatar: raftLogo, role: "Member", status: "online", playtime: "45m" },
            { id: "m-13", username: "RetroKing", avatar: cs2Logo, role: "Member", status: "offline" },
        ],
    },
    {
        id: "squad-5",
        name: "GTA Online — Cayo Perico & Casino Heist Crew",
        game: "Grand Theft Auto V",
        gameLogo: rdr2Logo,
        description: "Tuyển 3 anh em chạy chuỗi Heist Cayo Perico và Diamond Casino. Yêu cầu biết đường chạy stealth cơ bản, tiền chia đều 25% mỗi người không phân biệt Leader!",
        tags: ["💰 Heist", "GTA Online", "Stealth", "Equal Pay"],
        currentMembers: 4,
        maxMembers: 4,
        voice: "Discord Required",
        isMySquad: false,
        roomCode: "#GTA-HEIST-441",
        discordUrl: "https://discord.gg/gta-heist",
        createdAt: "1 ngày trước",
        status: "full",
        members: [
            { id: "m-14", username: "SunWukong", avatar: avatarDefault, role: "Leader", status: "in-game", playtime: "4h" },
            { id: "m-15", username: "DevCreator", avatar: raftLogo, role: "Member", status: "in-game", playtime: "4h" },
            { id: "m-16", username: "PixelQueen", avatar: cs2Logo, role: "Member", status: "in-game", playtime: "3h 30m" },
            { id: "m-17", username: "Alex_Dev", avatar: rdr2Logo, role: "Member", status: "in-game", playtime: "4h" },
        ],
    },
];
