import {
    DEFAULT_AVATAR as avatarGame,
    RAFT_SCREENSHOTS,
    BUTTERFLY_EMERALD_IMG as butterflyEmeraldImg,
    CS2_BG as dust2Img,
    FIGURES_IMG as figuresImg
} from "@/shared/constants/images";
const raftImg = RAFT_SCREENSHOTS[0];
import type { PostData } from "./types";


export const ALL_POSTS: PostData[] = [
    {
        id: 1,
        author: "User123",
        authorAvatar: avatarGame,
        authorRank: "pro",
        gameTag: "Raft",
        timeAgo: "2 giờ trước",
        title: "Setup base ngoài khơi cực chill sau 40 ngày sinh tồn",
        content:
            "Cuối cùng cũng build xong base 3 tầng, có cả khu trồng trọt và bẫy cá tự động. " +
            "Ai đang chơi Raft chia sẻ layout của mọi người xem nào!",
        images: [raftImg, dust2Img],
        tags: ["📸 Showcase / Media", "Raft", "Basebuilding", "Survival"],
        likes: 24,
        comments: 8,
        tab: "foryou",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 2,
        author: "GhostRider",
        authorAvatar: avatarGame,
        authorRank: "rookie",
        gameTag: "Red Dead Redemption 2",
        timeAgo: "5 giờ trước",
        title: "Bản mod đồ hoạ 4K mới ra, chạy siêu mượt cho RDR2",
        content:
            "Vừa test bản mod textures mới cho RDR2, cải thiện chất lượng ánh sáng ban đêm " +
            "đáng kể mà FPS không giảm nhiều. Để link tải mod ở comment cho anh em.",
        tags: ["💡 Thảo Luận & Guide", "RDR2", "Mods", "Graphics"],
        likes: 56,
        comments: 19,
        tab: "following",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 3,
        author: "TacticalGamer",
        authorAvatar: avatarGame,
        authorRank: "master",
        gameTag: "Counter Strike 2",
        timeAgo: "1 ngày trước",
        title: "Tips aim training cho người mới lên Premier CS2",
        content:
            "Chia sẻ routine warm-up 15 phút mỗi ngày giúp mình cải thiện aim rõ rệt sau 2 tuần. " +
            "Không cần app ngoài, chỉ cần deathmatch đúng cách và tập control recoil.",
        images: [figuresImg, butterflyEmeraldImg, dust2Img],
        tags: ["💡 Thảo Luận & Guide", "CS2", "Tips", "Aim"],
        likes: 132,
        comments: 41,
        tab: "foryou",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 4,
        author: "NightOwl",
        authorAvatar: avatarGame,
        authorRank: "elite",
        gameTag: "Raft",
        timeAgo: "30 phút trước",
        title: "Tuyển 2 bạn chơi Raft chế độ Hardcore coop tối nay!",
        content:
            "Cả squad hiện có 2 người onl mỗi tối từ 20h, cần tìm thêm 2 anh em chung chí hướng xây dựng hạm đội trên biển. Không toxic, có mic discord nhé!",
        images: [raftImg, raftImg, raftImg],
        tags: ["🤝 Tìm Đồng Đội", "Raft", "Coop", "Squad"],
        likes: 89,
        comments: 27,
        tab: "following",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 5,
        author: "ProSniper",
        authorAvatar: avatarGame,
        authorRank: "legend",
        gameTag: "Counter Strike 2",
        timeAgo: "3 giờ trước",
        title: "AWP no-scope highlight reel — 20 kills in one match",
        content:
            "Vừa có một trận siêu đỉnh với AWP tại Inferno, chia sẻ clip highlight cho mọi người xem. " +
            "Tất cả đều là no-scope xử lý nhanh trong nháy mắt!",
        images: [butterflyEmeraldImg],
        tags: ["📸 Showcase / Media", "CS2", "Highlight", "AWP"],
        likes: 340,
        comments: 88,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 6,
        author: "MapMaker",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Counter Strike 2",
        timeAgo: "12 giờ trước",
        title: "🏆 Giải đấu CS2 Community Open Autumn 2026 — Đăng ký ngay!",
        content:
            "BQT mở đăng ký giải đấu cộng đồng CS2 cho các team amateur và bán chuyên. Tổng giải thưởng 50.000.000 VNĐ. Các đội trưởng vào đọc kỹ thể lệ thi đấu và đăng ký line-up trước ngày 15/08 nhé!",
        images: [dust2Img],
        tags: ["📢 Thông Báo & Event", "CS2", "Compe", "Tournament"],
        likes: 512,
        comments: 143,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 7,
        author: "ViperKing",
        authorAvatar: avatarGame,
        authorRank: "pro",
        gameTag: "Valorant",
        timeAgo: "1 giờ trước",
        title: "Tìm 2 bạn chơi Controller/Initiator leo rank Ascendant tối nay",
        content:
            "Team hiện có 1 Duelist và 1 Sentinel, cần tìm 2 bạn call team tốt, không toxic, onl tầm 20h - 23h hàng ngày. Ai chơi để lại Riot ID hoặc discord add liền nha!",
        tags: ["🤝 Tìm Đồng Đội", "Valorant", "Ranked", "Ascendant"],
        likes: 45,
        comments: 18,
        tab: "foryou",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 8,
        author: "TarnishedOne",
        authorAvatar: avatarGame,
        authorRank: "rookie",
        gameTag: "Elden Ring",
        timeAgo: "4 giờ trước",
        title: "Xin hướng dẫn cách né combo của Promised Consort Radahn trong DLC?",
        content:
            "Mình đánh boss cuối DLC Shadow of the Erdtree đến phase 2 là bị clone chém không thấy đường né. Anh em đang dùng build khiên hay lăn né thế nào cho xin chút kinh nghiệm với!",
        tags: ["❓ Hỏi Đáp (Q&A)", "EldenRing", "BossFight", "DLC"],
        likes: 67,
        comments: 32,
        tab: "following",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 9,
        author: "CyberSamurai",
        authorAvatar: avatarGame,
        authorRank: "immortal",
        gameTag: "Cyberpunk 2077",
        timeAgo: "6 giờ trước",
        title: "Góc ảnh Night City lúc trời mưa với Path Tracing overdrive",
        content:
            "Chia sẻ bộ ảnh chụp bằng Photo Mode in-game tại quận Japantown và Afterlife. Đồ hoạ Cyberpunk 2077 kết hợp ray-tracing thực sự là một kiệt tác nghệ thuật!",
        tags: ["📸 Showcase / Media", "Cyberpunk", "Photography", "NightCity"],
        likes: 210,
        comments: 54,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 10,
        author: "SunWukong",
        authorAvatar: avatarGame,
        authorRank: "master",
        gameTag: "Black Myth: Wukong",
        timeAgo: "8 giờ trước",
        title: "Bí kíp hạ gục Nhị Lang Thần (Erlang Shen) không tốn bầu hồ lô",
        content:
            "Sử dụng Pháp Bảo Quạt Ba Tiêu kết hợp bộ giáp Tề Thiên để phá giáp siêu nhanh. Chi tiết chuỗi combo đòn đánh nặng và phân thân trong bài hướng dẫn này!",
        tags: ["💡 Thảo Luận & Guide", "Wukong", "Bosses", "Secret"],
        likes: 189,
        comments: 42,
        tab: "foryou",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 11,
        author: "LosSantosBro",
        authorAvatar: avatarGame,
        authorRank: "veteran",
        gameTag: "Grand Theft Auto V & Online",
        timeAgo: "3 giờ trước",
        title: "Tuyển anh em chạy Heist Cayo Perico & Casino chia đều 25% mỗi người",
        content:
            "Cần 3 đồng đội biết làm nhiệm vụ stealth, không bắn lung tung, đủ mic discord. Chuẩn bị bay vào việc luôn trong tối nay!",
        tags: ["🤝 Tìm Đồng Đội", "GTAV", "Heist", "FiveM"],
        likes: 72,
        comments: 29,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 12,
        author: "RedstoneMaster",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Minecraft Builders & Redstone",
        timeAgo: "10 giờ trước",
        title: "Hoàn thành lâu đài phong cách Gothic 10.000 khối sau 2 tháng solo",
        content:
            "Sử dụng BSL Shaders cùng Conquest texture pack. Lâu đài có đầy đủ nội thất từ hầm ngục đến tháp chuông. Để lại link tải map world save cho mọi người tham quan!",
        tags: ["📸 Showcase / Media", "Minecraft", "MegaBuild", "Shader"],
        likes: 420,
        comments: 95,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 13,
        author: "Valve_Official",
        authorAvatar: dust2Img,
        authorRank: "grandmaster",
        gameTag: "Counter Strike 2",
        timeAgo: "1 ngày trước",
        title: "📢 [VALVE OFFICIAL] Cập nhật lớn The Armory v1.40.2.0 - 3 Bộ Sưu Tập Vũ Khí & Cân bằng Recoil AK/M4",
        content:
            "Chúng tôi vui mừng ra mắt bản cập nhật The Armory v1.40.2.0 mang đến 3 bộ sưu tập vũ khí mới, hòm móc khóa Charms độc quyền, và điều chỉnh độ giật phục hồi của AK-47 cùng M4A1-S trên kiến trúc Sub-tick nhằm tăng tính chuẩn xác khi thi đấu đỉnh cao.",
        tags: ["📢 Thông Báo NPH", "CS2", "PatchNotes", "Update"],
        likes: 1850,
        comments: 342,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 14,
        author: "RockstarGames_NPH",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Red Dead Redemption 2",
        timeAgo: "3 ngày trước",
        title: "📢 [ROCKSTAR OFFICIAL] Bản Cập Nhật v1.32.0 - Tối ưu hóa DLSS 3.5 & FSR 3 cho PC",
        content:
            "Bản cập nhật v1.32.0 chính thức phát hành trên PC, bổ sung hỗ trợ NVIDIA DLSS 3.5 Ray Reconstruction và AMD FSR 3 Frame Generation, khắc phục các sự cố rò rỉ bộ nhớ khi chơi chế độ Story Mode thời gian dài.",
        tags: ["📢 Thông Báo NPH", "RDR2", "PatchNotes", "Update"],
        likes: 920,
        comments: 154,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 15,
        author: "RedbeetInteractive",
        authorAvatar: raftImg,
        authorRank: "grandmaster",
        gameTag: "Raft",
        timeAgo: "4 ngày trước",
        title: "📢 [REDBEET OFFICIAL] Bản Cập Nhật Mùa Hè v1.09 - Đảo Thần Bí & Sinh Vật Biển Mới",
        content:
            "Chào mừng các nhà thám hiểm đến với bản cập nhật v1.09! Khám phá quần đảo sương mù mới với sinh vật biển phát sáng, công thức nấu ăn cao cấp và đồ nội thất tự động hóa cho chiếc bè của bạn.",
        tags: ["📢 Thông Báo NPH", "Raft", "PatchNotes", "Update"],
        likes: 640,
        comments: 88,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 16,
        author: "CDPROJEKTRED",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Cyberpunk 2077",
        timeAgo: "2 ngày trước",
        title: "📢 [CD PROJEKT RED] Patch 2.20 - Mở Rộng Hệ Thống Metro & Tối Ưu Path Tracing",
        content:
            "Patch 2.20 mang đến hệ thống tàu điện ngầm NCART tương tác đầy đủ, các tương tác mới tại căn hộ của V, và nâng cấp hiệu năng Path Tracing với Ray Reconstruction mượt mà hơn trên mọi dòng card đồ họa.",
        tags: ["📢 Thông Báo NPH", "Cyberpunk", "PatchNotes", "Update"],
        likes: 1250,
        comments: 210,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 17,
        author: "RiotGames_NPH",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Valorant",
        timeAgo: "1 ngày trước",
        title: "📢 [RIOT GAMES OFFICIAL] Patch Notes 9.08 - Rework Bản Đồ Pearl & Cân Bằng Agent Vyse",
        content:
            "Patch 9.08 chính thức ra mắt: Làm lại khu vực B-Site trên bản đồ Pearl, giảm thời gian làm chậm từ bẫy của Vyse, đồng thời cải thiện hệ thống Vanguard chống gian lận cấp độ phần cứng.",
        tags: ["📢 Thông Báo NPH", "Valorant", "PatchNotes", "Update"],
        likes: 1420,
        comments: 310,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 18,
        author: "FromSoftware_NPH",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Elden Ring",
        timeAgo: "5 ngày trước",
        title: "📢 [FROMSOFTWARE OFFICIAL] Regulation Patch 1.14 - Cân Bằng Shadow of the Erdtree",
        content:
            "Regulation Patch 1.14 tinh chỉnh sát thương và độ cơ động của các Boss cuối trong bản mở rộng Shadow of the Erdtree, tăng chỉ số phòng thủ khi thu thập Scadutree Fragment tại mức 1-10.",
        tags: ["📢 Thông Báo NPH", "EldenRing", "PatchNotes", "Update"],
        likes: 2100,
        comments: 480,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 19,
        author: "GameScience_NPH",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Black Myth: Wukong",
        timeAgo: "3 ngày trước",
        title: "📢 [GAME SCIENCE OFFICIAL] Patch v1.0.8 - Khắc Phục Lỗi Dừng Hình & Tối Ưu Ray Tracing",
        content:
            "Bản cập nhật v1.0.8 tập trung xử lý hiện tượng sụt giảm khung hình tại chương 3 và chương 4, cải thiện chất lượng phản chiếu Full Ray Tracing trên PC và hệ thống âm thanh vòm PS5.",
        tags: ["📢 Thông Báo NPH", "Wukong", "PatchNotes", "Update"],
        likes: 3120,
        comments: 540,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 20,
        author: "RockstarNorth",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Grand Theft Auto V & Online",
        timeAgo: "4 ngày trước",
        title: "📢 [ROCKSTAR OFFICIAL] GTA Online: Bottom Dollar Bounties Update - Mở Rộng Săn Tiền Thưởng",
        content:
            "Tham gia cùng Maude Eccles trong bản cập nhật mới nhất của GTA Online. Sở hữu văn phòng săn tiền thưởng riêng, truy bắt các mục tiêu truy nã giá trị cao và mở khóa hàng loạt siêu xe mới.",
        tags: ["📢 Thông Báo NPH", "GTAV", "PatchNotes", "Update"],
        likes: 1890,
        comments: 290,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 21,
        author: "MojangStudios",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Minecraft Builders & Redstone",
        timeAgo: "2 ngày trước",
        title: "📢 [MOJANG OFFICIAL] Tricky Trials Update v1.21 - Hầm Ngục Thử Thách & Vũ Khí Mace",
        content:
            "Khám phá Trial Chambers thần bí, chiến đấu với quái vật Breeze mới, chế tạo vũ khí Mace hạng nặng cùng công cụ chế tạo tự động Crafter bằng Redstone trong bản cập nhật v1.21 chính thức!",
        tags: ["📢 Thông Báo NPH", "Minecraft", "PatchNotes", "Update"],
        likes: 2450,
        comments: 410,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
];